### ISSUE TITLE
安装后无法启动webman

### ISSUE THREAD

**Issue by luckydate2021** [majie721/webmanenv#1]
安装后无法启动webman，提示
PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in /Users/mac/www/home/wwwroot/webman/vendor/majie721/webmanenv/src/EnvLoader.php on line 11

**Comment by luckydate2021** [comment]
mac php7.4

**Comment by weaverer** [comment]
升级php8.0,用8.0的写的
