### ISSUE TITLE
安装完使用的时候报错

### ISSUE THREAD

**Issue by ximengyi** [majie721/webmanenv#2]
PHP Parse error:  syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE) in /root/work/testdemo/vendor/majie721/webmanenv/src/EnvLoader.php on line 11 ,

**Comment by weaverer** [comment]
升级php8.0,用8.0的写的

**Comment by weaverer** [comment]
升级php8.0
